import {
  EnvironmentalConditions,
  InspectionMetadata,
  InstrumentData,
  MetroCertifyState,
  RawTestPointInput,
} from '../types/metrology';

export interface PresetScenario {
  id: string;
  name: string;
  badge: string;
  badgeColor: string;
  description: string;
  data: MetroCertifyState;
}

export const PRESET_SCENARIOS: PresetScenario[] = [
  {
    id: 'class_iii_retail_15kg_pass',
    name: 'Class III 15kg Retail Scale (Compliant)',
    badge: 'Standard Trade Scale',
    badgeColor: 'bg-emerald-100 text-emerald-800 border-emerald-300',
    description:
      'Standard counter weighing instrument tested at RRSL Ahmedabad. Ascending and descending load cycles comply with OIML R 76-1:2006.',
    data: {
      instrument: {
        manufacturer: 'Avery Weigh-Tronix Metrology Ltd.',
        model: 'RetailMaster POS-15K',
        serialNumber: 'IND/RRSL-AHM/2026/0892',
        accuracyClass: 'class_III',
        maxCapacity: 15,
        minCapacity: 0.1,
        verificationInterval: 0.005, // e = 5g
        actualDivision: 0.005, // d = 5g
        unit: 'kg',
        scaleIntervalCount: 3000,
        deviceType: 'Electronic Price Computing Counter Scale',
      },
      environment: {
        temperature: 23.4,
        humidity: 54.0,
        pressure: 1012.8,
        voltage: 230.2,
      },
      inspection: {
        labName: 'Regional Reference Standard Laboratory (RRSL), Ahmedabad',
        labLocation: 'Western Region, Ministry of Consumer Affairs, India',
        officerName: 'Er. Rajesh Kumar Sharma',
        officerDesignation: 'Senior Metrological Officer (Legal Metrology)',
        approverName: 'Dr. Sunita Deshmukh',
        approverDesignation: 'Director & Head of Laboratory, RRSL',
        certificateNumber: 'RRSL/AHM/NAWI/2026/0491',
        testDate: '2026-09-08',
        verificationType: 'initial',
      },
      testPoints: [
        // ASCENDING CYCLE
        {
          id: 'p-asc-0',
          sequence: 'ascending',
          stepLabel: 'Zero (0)',
          appliedLoad: 0,
          indication: 0.0,
          addedLoad: 0.002, // P0 = 0 + 0.0025 - 0.002 = 0.0005 kg (+0.1e)
          notes: 'Zero-setting and tare verification',
        },
        {
          id: 'p-asc-1',
          sequence: 'ascending',
          stepLabel: 'Min (100g)',
          appliedLoad: 0.1,
          indication: 0.1,
          addedLoad: 0.002,
          notes: 'Minimum capacity limit (20e)',
        },
        {
          id: 'p-asc-2',
          sequence: 'ascending',
          stepLabel: '500e (2.5kg)',
          appliedLoad: 2.5,
          indication: 2.5,
          addedLoad: 0.0015,
          notes: 'MPE transition boundary 1 (±0.5e)',
        },
        {
          id: 'p-asc-3',
          sequence: 'ascending',
          stepLabel: '1000e (5kg)',
          appliedLoad: 5.0,
          indication: 5.0,
          addedLoad: 0.001,
          notes: 'Intermediate verification load',
        },
        {
          id: 'p-asc-4',
          sequence: 'ascending',
          stepLabel: '1500e (7.5kg)',
          appliedLoad: 7.5,
          indication: 7.5,
          addedLoad: 0.0005,
          notes: '50% Max Capacity',
        },
        {
          id: 'p-asc-5',
          sequence: 'ascending',
          stepLabel: '2000e (10kg)',
          appliedLoad: 10.0,
          indication: 10.0,
          addedLoad: 0.0035,
          notes: 'MPE transition boundary 2 (±1.0e)',
        },
        {
          id: 'p-asc-6',
          sequence: 'ascending',
          stepLabel: 'Max (15kg)',
          appliedLoad: 15.0,
          indication: 15.0,
          addedLoad: 0.004,
          notes: 'Full capacity test load (3000e)',
        },
        // DESCENDING CYCLE
        {
          id: 'p-desc-0',
          sequence: 'descending',
          stepLabel: 'Max (15kg)',
          appliedLoad: 15.0,
          indication: 15.0,
          addedLoad: 0.0035,
          notes: 'Unloading top load point',
        },
        {
          id: 'p-desc-1',
          sequence: 'descending',
          stepLabel: '2000e (10kg)',
          appliedLoad: 10.0,
          indication: 10.0,
          addedLoad: 0.003,
          notes: 'Unloading upper transition',
        },
        {
          id: 'p-desc-2',
          sequence: 'descending',
          stepLabel: '1000e (5kg)',
          appliedLoad: 5.0,
          indication: 5.0,
          addedLoad: 0.0015,
          notes: 'Unloading mid load',
        },
        {
          id: 'p-desc-3',
          sequence: 'descending',
          stepLabel: 'Min (100g)',
          appliedLoad: 0.1,
          indication: 0.1,
          addedLoad: 0.002,
          notes: 'Unloading minimum limit',
        },
        {
          id: 'p-desc-4',
          sequence: 'descending',
          stepLabel: 'Zero Return (0)',
          appliedLoad: 0,
          indication: 0.0,
          addedLoad: 0.0022,
          notes: 'Hysteresis & zero-point return verification',
        },
      ],
    },
  },
  {
    id: 'class_ii_lab_600g_pass',
    name: 'Class II 600g Precision Balance (Compliant)',
    badge: 'High Precision Metrology',
    badgeColor: 'bg-blue-100 text-blue-800 border-blue-300',
    description:
      'High accuracy Class II analytical balance tested at RRSL Bengaluru for pharmaceutical calibration compliance.',
    data: {
      instrument: {
        manufacturer: 'Sartorius Metrology India Pvt Ltd',
        model: 'Secura Analytical Pro 600',
        serialNumber: 'IND/RRSL-BLR/2026/0411',
        accuracyClass: 'class_II',
        maxCapacity: 600,
        minCapacity: 0.5,
        verificationInterval: 0.01, // e = 0.01g (10mg)
        actualDivision: 0.001, // d = 0.001g (1mg)
        unit: 'g',
        scaleIntervalCount: 60000,
        deviceType: 'High Precision Electromagnetic Force Compensation Balance',
      },
      environment: {
        temperature: 20.8,
        humidity: 48.5,
        pressure: 1013.2,
        voltage: 230.0,
      },
      inspection: {
        labName: 'Regional Reference Standard Laboratory (RRSL), Bengaluru',
        labLocation: 'Southern Region, Ministry of Consumer Affairs, India',
        officerName: 'Smt. K. Ananthalakshmi',
        officerDesignation: 'Senior Scientific Officer (Metrology)',
        approverName: 'Shri R. V. Chandrasekhar',
        approverDesignation: 'Director of Legal Metrology, RRSL Bengaluru',
        certificateNumber: 'RRSL/BLR/NAWI-II/2026/0188',
        testDate: '2026-09-08',
        verificationType: 'initial',
      },
      testPoints: [
        {
          id: 'p2-asc-0',
          sequence: 'ascending',
          stepLabel: 'Zero (0g)',
          appliedLoad: 0,
          indication: 0.0,
          addedLoad: 0.0004,
          notes: 'Class II zero stability check',
        },
        {
          id: 'p2-asc-1',
          sequence: 'ascending',
          stepLabel: 'Min (0.5g / 50e)',
          appliedLoad: 0.5,
          indication: 0.5,
          addedLoad: 0.0004,
          notes: 'Minimum capacity limit (50e)',
        },
        {
          id: 'p2-asc-2',
          sequence: 'ascending',
          stepLabel: '5000e (50g)',
          appliedLoad: 50.0,
          indication: 50.0,
          addedLoad: 0.0003,
          notes: 'Step 1 MPE transition limit (±0.5e)',
        },
        {
          id: 'p2-asc-3',
          sequence: 'ascending',
          stepLabel: '20000e (200g)',
          appliedLoad: 200.0,
          indication: 200.0,
          addedLoad: 0.0002,
          notes: 'Step 2 MPE transition limit (±1.0e)',
        },
        {
          id: 'p2-asc-4',
          sequence: 'ascending',
          stepLabel: '40000e (400g)',
          appliedLoad: 400.0,
          indication: 400.0,
          addedLoad: 0.0008,
          notes: 'Two-thirds capacity point',
        },
        {
          id: 'p2-asc-5',
          sequence: 'ascending',
          stepLabel: 'Max (600g / 60000e)',
          appliedLoad: 600.0,
          indication: 600.0,
          addedLoad: 0.0009,
          notes: 'Max load test (±1.5e limit)',
        },
        {
          id: 'p2-desc-0',
          sequence: 'descending',
          stepLabel: 'Max (600g)',
          appliedLoad: 600.0,
          indication: 600.0,
          addedLoad: 0.0008,
          notes: 'Unloading top point',
        },
        {
          id: 'p2-desc-1',
          sequence: 'descending',
          stepLabel: '20000e (200g)',
          appliedLoad: 200.0,
          indication: 200.0,
          addedLoad: 0.0003,
          notes: 'Unloading hysteresis check',
        },
        {
          id: 'p2-desc-2',
          sequence: 'descending',
          stepLabel: 'Zero Return (0g)',
          appliedLoad: 0,
          indication: 0.0,
          addedLoad: 0.00045,
          notes: 'Return to zero verification',
        },
      ],
    },
  },
  {
    id: 'class_iii_audit_fail',
    name: 'Class III 30kg Scale (OUT-OF-TOLERANCE / FAIL)',
    badge: 'Legal Metrology Audit Defect',
    badgeColor: 'bg-rose-100 text-rose-800 border-rose-300',
    description:
      'Field inspection scale failing OIML R 76-1 Clause 3.5.1 at high loads due to load cell strain gauge nonlinearity. Demonstrates automated rejection & violation highlighting.',
    data: {
      instrument: {
        manufacturer: 'Apex Industrial Instruments',
        model: 'Platform Scale Benchmark 30K',
        serialNumber: 'IND/AUDIT-REJECT/2026/9941',
        accuracyClass: 'class_III',
        maxCapacity: 30,
        minCapacity: 0.2,
        verificationInterval: 0.01, // e = 10g
        actualDivision: 0.01, // d = 10g
        unit: 'kg',
        scaleIntervalCount: 3000,
        deviceType: 'Bench Platform Scale with Single-Point Load Cell',
      },
      environment: {
        temperature: 28.2,
        humidity: 65.0,
        pressure: 1009.5,
        voltage: 218.0,
      },
      inspection: {
        labName: 'RRSL Regional Verification Unit, New Delhi',
        labLocation: 'Northern Region, Department of Legal Metrology',
        officerName: 'Shri Vikramaditya Rathore',
        officerDesignation: 'Assistant Controller of Legal Metrology',
        approverName: 'Dr. Manpreet Singh Sandhu',
        approverDesignation: 'Joint Director (Standards & Enforcement)',
        certificateNumber: 'RRSL/DEL/DEFECT-R76/2026/004',
        testDate: '2026-09-08',
        verificationType: 'initial',
      },
      testPoints: [
        {
          id: 'p3-asc-0',
          sequence: 'ascending',
          stepLabel: 'Zero (0kg)',
          appliedLoad: 0,
          indication: 0.0,
          addedLoad: 0.005, // E0 = 0.000
          notes: 'Zero check acceptable',
        },
        {
          id: 'p3-asc-1',
          sequence: 'ascending',
          stepLabel: 'Min (0.2kg)',
          appliedLoad: 0.2,
          indication: 0.2,
          addedLoad: 0.005,
          notes: 'Low load within range',
        },
        {
          id: 'p3-asc-2',
          sequence: 'ascending',
          stepLabel: '500e (5kg)',
          appliedLoad: 5.0,
          indication: 5.0,
          addedLoad: 0.004,
          notes: 'Marginal pass at 500e boundary',
        },
        {
          id: 'p3-asc-3',
          sequence: 'ascending',
          stepLabel: '1000e (10kg)',
          appliedLoad: 10.0,
          indication: 10.01,
          addedLoad: 0.001, // Excessive positive drift
          notes: 'Drift detected (+1.4e vs limit 1.0e - BREACH)',
        },
        {
          id: 'p3-asc-4',
          sequence: 'ascending',
          stepLabel: '2000e (20kg)',
          appliedLoad: 20.0,
          indication: 20.02,
          addedLoad: 0.001, // P = 20.02 + 0.005 - 0.001 = 20.024 -> Ec = +0.024kg (+2.4e vs limit 1.0e - CRITICAL BREACH)
          notes: 'Strain gauge nonlinearity error (MPE Exceeded)',
        },
        {
          id: 'p3-asc-5',
          sequence: 'ascending',
          stepLabel: 'Max (30kg)',
          appliedLoad: 30.0,
          indication: 30.03,
          addedLoad: 0.002,
          notes: 'Full load severe drift (+2.8e vs limit 1.5e)',
        },
      ],
    },
  },
];
